version: '3.8'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
#
#networks:
#  monitoring:
#    driver: bridge
#
#services:
#  postgres:
#    image: postgres:latest
#    container_name: libotanic
#    ports:
#      - "5433:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=${PGUSER}
#      - POSTGRES_PASSWORD=${PGPASSWORD}
#      - POSTGRES_DB=${PDDATABASE}
  