#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.format_sql=true

spring:
  datasource:
    url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
           #jdbc:postgresql://containers-us-west-163.railway.app:5858/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    show-sql: true

springdoc:
    packagesToScan: ru.tinkoff.academy.libotanic

